CREATE TABLE SHIPWRECK(
	ID INT IDENTITY(1,1),
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
	CONDITION VARCHAR(255),
	DEPTH INT,
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	YEAR_DISCOVERED INT
);
INSERT INTO SHIPWRECK
(NAME, DESCRIPTION, CONDITION, DEPTH, LATITUDE, LONGITUDE, YEAR_DISCOVERED)
VALUES
('Admin User1', 'admin@gmail.com', 'admin', 123,1234,12234,134242);